name: deepchem
channels:
  - conda-forge
  - deepchem
  - omnia
  - defaults
dependencies:
  - python==3.7.*
  - tensorflow==1.13.*
  - deepchem==2.2.*
  - jupyterlab
  - pip
  - pip:
     - dlhub_sdk

